### ISSUE TITLE
Suggestion: PlayerOnly annotation

### ISSUE THREAD

**Issue by harry0198** [ipsk/MattFramework#3]
So instead of having to include a instanceof Player check in our code - it would be nice to just have an annotation such as
@PlayerOnly

**Comment by harry0198** [comment]
Never mind alias works

**Comment by ipsk** [comment]
@harry0198 There is no need for that as it is already included if you don't want console to access the command instead of using `CommandSender` you can use `Player` as your first parameter, this will automatically deny any console attempts.
