### ISSUE TITLE
[Suggestion] Add note about NOT registering command(s) in plugin.yml

### ISSUE THREAD

**Issue by Andre601** [ipsk/MattFramework#4]
The documentation/wiki is okay, but misses one crucial piece on information, which is to point out, that the command you set, shouldn't be registered through the plugin.yml as this will automatically override the registration of the framework and break the command entirely.

**Comment by ipsk** [comment]
Fixed on cd9e732c533752f262c888a458ff1b52dd6a6535 you can now register in the plugin.yml fine!

**Comment by ipsk** [comment]
Released `1.3` with this change.
